Faster logging
rahularya50/scheme_interpreter_personal pull request #153
Opened 2019-04-13 03:50 UTC by rahularya50

2019-04-13 05:17 UTC, kavigupta commented
```
(define (flatmap f x)
  (define (h z x)
    (if (null? x)
        z
        (h (append (f (car x)) z) (cdr x))))
  (h nil x))

(define (expand lst)
  (flatmap (lambda (x)
             (cond 
               ((equal? x 'x) '(x r y f r))
               ((equal? x 'y) '(l f x l y))
               (else          (list x))))
           lst))

(define (interpret instr dist)
  (define (go inst)
    (cond 
      ((equal? 'f inst) (fd dist))
      ((equal? 'r inst) (rt 90))
      ((equal? 'l inst) (lt 90))))
  (map go instr))

(define (apply-many n f x)
  (if (zero? n)
      x
      (apply-many (- n 1) f (f x))))

(define (dragon n d)
  (interpret (apply-many n expand '(f x)) d))
```

`(apply-many 7 expand '(f x))` still takes forever (compare to staff.py's speed). Is there any way to make this faster?

2019-04-15 11:29 UTC, kavigupta requested changes

2019-04-15 11:29 UTC, kavigupta commented on editor/evaluate_apply.py
> +            log.logger.eval_stack.append("cat")  # TODO: f"{repr(expr)} [frame = {frame.id}]")
uh...

2019-04-15 17:41 UTC, rahularya50 commented on editor/evaluate_apply.py
> +            log.logger.eval_stack.append("cat")  # TODO: f"{repr(expr)} [frame = {frame.id}]")
whoops

2019-04-15 19:56 UTC, kavigupta approved these changes

2019-04-15 19:57 UTC, merged