Don't shadow special forms
rahularya50/scheme_interpreter_personal pull request #63
Opened 2019-03-21 09:44 UTC by rahularya50

Fixes #60

2019-03-21 09:46 UTC, rahularya50 commented
Please test this thoroughly - I'll do so as well. It passes the automated tests, but I'm very scared of making such a significant modification to the interpreter.

The significant change (other than what the PR is about) is that I now instantiate a special form Callable instance at _lookup time_, rather than during initialization. I don't think this should affect anything, since the Callable instance should never be accessible, but I'm not 100%.

2019-03-21 10:05 UTC, rahularya50 commented
The following is a brief overview of how lookup of builtins / special forms works, which I'm writing just for my own understanding, but I might as well put it here:

**evaluate_apply.py**
 - Anything that can be called (builtins, procedures, special forms) extends `Callable`.
 - Anything that can be _applied_ (i.e. evaluates all its arguments) extends `Applicable`, which itself extends `Callable`.
 - The frame containing all the builtin procedures (arithmetic, type checking, etc.) is the `Builtins` frame, which is the parent frame of the `Global` frame. The `Builtins` frame is the only frame with no parent frame.

**environment.py**
 - To initialize these frames, two class decorators exist - `global_attr`, and `special_form`. **The `special_form` decorator is new.**  Both decorators take a single argument and put the class they're decorating in a dict. These decorators can be chained.
 - These decorators are both generated by the `make_frame_decorator(defdict)` function, which stores all the decorated functions in `defdict`, which associates a string with each decorated class.
 - All the classes decorated by `global_attr` go in the dictionary `defdict`, while all the classes decorated by `special_form` go in the dictionary `special_forms`.
 - When a new Scheme environment is started, the function `make_global_frame()` is called. It iterates through all the elements of `defdict`, instantiates each class to produce an instance of `Callable`, and puts it in the `Builtins` frame, which is then set to be the parent of `Globals`.

**evaluate_apply.py**
 - When a `Symbol` is evaluated, we just search in the current environment as usual. **This will not return any special forms, since special forms were not added to the ``Builtins`` frame, but only to the dictionary ``special_forms``**.
 - When a `Pair` is evaluated, we first check if the first element of the `Pair` is a `Symbol`. If so, we call `get_special_form` from `environment.py`, which tries to find the special form class in `special_forms`, and returns a new instance of one if it is found. (otherwise it returns `False`)
 - Otherwise, we evaluate the first element of the `Pair` recursively as normal.

2019-03-29 07:59 UTC, kavigupta requested changes

2019-03-29 07:59 UTC, kavigupta commented on editor/environment.py
> +        return False
Should probably be `None` by python conventions

2019-03-29 07:59 UTC, kavigupta commented on editor/special_forms.py
> +@special_form("unquote")
Seems strange to add unquote in this PR

2019-03-30 08:13 UTC, kavigupta requested changes

2019-03-30 08:13 UTC, kavigupta commented on editor/special_forms.py
> +    CallableResolutionError
what's this import for?

2019-03-30 08:17 UTC, rahularya50 commented on editor/special_forms.py
> +    CallableResolutionError
No idea. Removed.

2019-03-30 08:44 UTC, kavigupta approved these changes

2019-03-30 08:56 UTC, merged